/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#eaf1ff',
        'surface-container-low': '#eff4ff',
        'on-primary-fixed': '#002115',
        'on-secondary-fixed': '#111c2d',
        'tertiary-fixed': '#cce5ff',
        'on-background': '#0b1c30',
        'on-secondary-fixed-variant': '#3c475a',
        'outline-variant': '#bdc9c1',
        'on-surface-variant': '#3e4943',
        tertiary: '#005683',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#bcc7de',
        'secondary-container': '#d5e0f8',
        'surface-container-highest': '#d3e4fe',
        'on-secondary-container': '#586377',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        surface: '#f8f9ff',
        'on-tertiary-container': '#dbecff',
        'surface-tint': '#006c4e',
        'on-primary-container': '#9ffdd3',
        error: '#ba1a1a',
        'primary-container': '#047857',
        'surface-container-high': '#dce9ff',
        'surface-bright': '#f8f9ff',
        'primary-fixed-dim': '#7bd8b1',
        'surface-variant': '#d3e4fe',
        'inverse-primary': '#7bd8b1',
        'tertiary-container': '#006fa8',
        'on-primary': '#ffffff',
        'on-surface': '#0b1c30',
        'surface-container': '#e5eeff',
        'inverse-surface': '#213145',
        'on-error-container': '#93000a',
        'primary-fixed': '#97f5cc',
        secondary: '#545f73',
        'on-tertiary-fixed': '#001d31',
        'tertiary-fixed-dim': '#93ccff',
        outline: '#6e7a73',
        'on-primary-fixed-variant': '#00513a',
        background: '#f8f9ff',
        'secondary-fixed': '#d8e3fb',
        'on-tertiary-fixed-variant': '#004b73',
        primary: '#005d42',
        'surface-dim': '#cbdbf5',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
      },
      spacing: {
        gutter: '1rem',
        'space-md': '0.75rem',
        'space-sm': '0.5rem',
        'space-xl': '2rem',
        'space-lg': '1.25rem',
        margin: '1rem',
        'space-xs': '0.25rem',
        'gutter-desktop': '1.5rem',
        'margin-desktop': '2rem',
      },
      fontFamily: {
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'tabular-data': ['Inter', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'tabular-data': ['13px', { lineHeight: '18px', letterSpacing: '0em', fontWeight: '500' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '12px', letterSpacing: '0.04em', fontWeight: '700' }],
        'body-md': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
